### ISSUE TITLE
sp_metadata url

### ISSUE THREAD

**Issue by mabahma** [xcgd/auth_saml#7]
Hello

I installed auth_saml module and lasso.

I don't know how to build sp_metadata url ?

Do you have an idea ?

Kind regards,

**Comment by houzefa-abba** [comment]
Hey,

The "IDP configuration" box contains information and URLs about the identity provider. We usually test with [Authentic 2](https://www.entrouvert.com/en/digital-identity/authentic-2/).

The "SP configuration" box contains information and URLs about the service provider (which is Odoo, in this case).

The demo setup assumes an IDP running on `localhost:8000` and an SP (Odoo) running on `localhost:8069`.

There is also some documentation [here](https://github.com/xcgd/auth_saml/blob/github_odoo9/doc/getting_started.rst).

Hope this helps

**Comment by mabahma** [comment]
Hi than you for your answer..

I'm using odoo9  behind ngix  , https and another IDP.

Yes of course i changed the value in every box , but in ''SP Conf'' one.

 
----------------------

<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                     validUntil="2017-03-22T10:33:37Z"
                     cacheDuration="PT604800S"
                     **entityID="https://my-odoo-server/metadata">**
    <md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"                             Location="https://my-idp-server/Saml2/POST"
                                     index="1" />
        
    </md:SPSSODescriptor>
</md:EntityDescriptor>

-----------------------


normally if every thing was ok, https://my-odoo-server/metadata  should give me xml file, but i have 404 response..
i also have tested with :  https://my-odoo-server:8069/metadata and had the same..

Any idea on how to generate this url (or how it is should be generated) ?

kind regards

**Comment by houzefa-abba** [comment]
Right... That URL should simply show the contents of the "SP configuration" box, with an HTTP content-type set to `text/xml`.

This module does not currently provide it as we usually copy-and-paste that SP configuration directly into our IDP server, so the IDP server then does not even have to call the `metadata` URL to get the info.

This should definitely be added to this module; to be done in `controllers/main.py`. Patch welcome! =)

**Comment by yasii1991** [comment]
Hi,

I tried using this module with a Shibboleth IDP but there seems to be a problem. Even after using an original certificate of the IDP in IDP metadata, it seems to be throwing couldn't verify signature error. I already mailed you regarding this Houzefa, and also all the other authors, but there seems to be no reply yet. Would be great if anyone who has used this module successfully could comment regarding it.

**Comment by mabahma** [comment]
Hi,
I succeded to make it work using lasso plugin and another IDP.

The only issue i had is that i was using signed certificate so i had to upload it to my IDP

<<if your service provider signs their authentication requests then you may upload their signing certificate to verify that the requests come from a trusted source.
>>

**Comment by gridworkz** [comment]
Hi:
Could you share more details on how you made this work? What IdP server did you use? Has anyone got this working with Shibboleth IdP? What is the name of the SP metadata file that you copy to the IdP server? Cheers, Dave

**Comment by mabahma** [comment]
Hello,

I managed to link odoo using SAML with another idp (Dell one Identity manager).

I had to install lasso as explained in this link 

http://authentic2.readthedocs.io/en/stable/installation_modes.html#install-lasso-ref

I remember i had some issues to istall it, but i googled and worked them out.

Then have done some minor modification to odoo login page.

I have created a saml provider in odoo under configuration.

And last, i configured the saml link in my IDP and it worked (you should do the same in shibolteh).
 

Hope this will help you , if not i can give you more details.

**Comment by gridworkz** [comment]
Hi:

Thanks for getting back so quickly. I'm going to checkout the steps you've
outlined and I'm also going to put together a HOW-TO on this so I'll
probably need some more details. But I'll document the steps I go through
to build everything. If you could share the modifications you made to the
Odoo login page that would be very helpful. Also if you could give me the
exact SAML link you put in your IdP then I'll do the same in Shibboleth and
document that. Thanks again for taking the time to address this.

Cheers,
Dave

**Comment by gridworkz** [comment]
Sorry for the second email - also if you could copy/paste the entries you
made into the auth-saml plugin in Odoo (the Idp metadata and SP metadata
minus your certs and actual links, just put in dummy placeholders). That
would also be really helpful.
Cheers,
Dave

**Comment by gridworkz** [comment]
Hello:
*Update*
I now have a functioning Shibboleth Idp returning the uid Attribute and a NameId. The NameId is formatted as a PersistentId and is BASE32 encoded. That's what is giving the Error3 - Access Denied message in the Odoo logs, the auth_saml plugin is not decoding the NameId properly. Can you confirm that you're matching on subject.nameid in your Odoo auth_saml configuration? I think I'm real close. Cheers, Dave

**Comment by gridworkz** [comment]
We're up and running now. Just had to decode the nameid.
