### ISSUE TITLE
odoo 11 

### ISSUE THREAD

**Issue by mrks-grsh** [xcgd/auth_saml#8]
Hi

Is there an updated version for odoo 11 ?

THANKS
Markus

**Comment by abhi-krishnan** [comment]
Yes Odoo 11 is now released

When you try to install or configure create a new postgress user and try it,else it will shows errors

**Comment by mrks-grsh** [comment]
please commit branch for odoo 11
THANKS

**Comment by abhi-krishnan** [comment]
pleae go through this link here you can get it according to your OS. https://www.odoo.com/page/download

**Comment by houzefa-abba** [comment]
Hi,

Odoo 11 has indeed been released but this `auth_saml` module has not yet been ported to work with Odoo 11.

If you are feeling up to the task, please go ahead!

Note: The latest `auth_saml` code is [on bitbucket](https://bitbucket.org/xcg/auth_saml).

**Comment by max3903** [comment]
Hello,

@ursais would be interested to migrate it to Odoo 11 and push it to https://github.com/OCA/server-auth.

Any problem with that? Would you sign the OCA CLA? Do you have an idea of the effort?

CC: @jgrandguillaume, @wolfhall

**Comment by jgrandguillaume** [comment]
Hi @faide may be you can give your opinion here :) ?

**Comment by houzefa-abba** [comment]
Sure, go ahead!

Please fork from <https://bitbucket.org/xcg/auth_saml> & submit there, as that is the most up-to-date repo.

We had a PR over at <https://github.com/OCA/server-tools/pull/274> for OCA integration but it has since been closed due to lack of interest. Feel free to follow up on it as well. =)

**Comment by max3903** [comment]
FYI
https://github.com/OCA/server-auth/pull/12

**Comment by vincent-hatakeyama** [comment]
auth_saml for odoo 11 is present in https://github.com/OCA/server-auth
